POST http://localhost:8000/

ping

######

######
GET  http://localhost:3000/api/v1/users/

######
GET  http://localhost:3000/home

######
POST   http://localhost:3000/
Content-Type: application/json

{
    "key":"value"
}


######
DELETE  http://localhost:3000/

######
PUT  http://localhost:3000/